{% set name = "django-plotly-wagtail" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3236dbfef31bc0c5dc9cc397177f1e746eeefb20493a127e0a9eb0458ddbb8f6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - django >3.2
    - django-plotly-dash
    - wagtail
    - dash-bootstrap-components
    - dash-core-components
    - dash-html-components
    - dash-table

test:
  imports:
    - dpwagtail
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/GibbsConsulting/django-plotly-wagtail
  summary: Django Wagtail use of django-plotly-dash and plotly dash
  dev_url: https://gitlab.com/GibbsConsulting/django-plotly-wagtail
  license: NGPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
